/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function HeartGl(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Heart.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="transform1" />
        <group name="hearttransform1" />
        <group name="directionalLight1" position={[-167.96, 0, 159]} rotation={[-Math.PI, -0.64, -Math.PI]} scale={17.93} />
        <group name="directionalLight2" position={[165.68, 0, 150.5]} rotation={[0, 0.43, 0]} scale={17.93} />
        <group name="Mash_heart_instancer_objects">
          <mesh name="myPlane258Shape_Mash_heart_instancer_0" geometry={nodes.myPlane258Shape_Mash_heart_instancer_0.geometry} material={materials.aiStandardSurface3} position={[-5.57, 11, -33.38]} rotation={[1.35, 0.78, -0.27]} scale={0.11} />
          <mesh name="myPlane263Shape_Mash_heart_instancer_1" geometry={nodes.myPlane263Shape_Mash_heart_instancer_1.geometry} material={materials.aiStandardSurface3} position={[-1.95, 11.86, -35.32]} rotation={[1.91, 0.91, -1.28]} scale={0.07} />
          <mesh name="myPlane257Shape_Mash_heart_instancer_2" geometry={nodes.myPlane257Shape_Mash_heart_instancer_2.geometry} material={materials.aiStandardSurface3} position={[-6.87, 14.13, -35.43]} rotation={[0.79, 0.93, -0.22]} scale={0.07} />
          <mesh name="myPlane259Shape_Mash_heart_instancer_3" geometry={nodes.myPlane259Shape_Mash_heart_instancer_3.geometry} material={materials.aiStandardSurface3} position={[-12.02, 13.6, -35.36]} rotation={[-1.14, 1.25, 1.85]} scale={0.07} />
          <mesh name="myPlane262Shape_Mash_heart_instancer_4" geometry={nodes.myPlane262Shape_Mash_heart_instancer_4.geometry} material={materials.aiStandardSurface3} position={[-15.75, 11.08, -35.38]} rotation={[2.25, -0.97, 1.36]} scale={0.07} />
          <mesh name="myPlane268Shape_Mash_heart_instancer_5" geometry={nodes.myPlane268Shape_Mash_heart_instancer_5.geometry} material={materials.aiStandardSurface3} position={[-18.11, 6.28, -35.44]} rotation={[-1.1, 0.57, 2.15]} scale={0.08} />
          <mesh name="myPlane261Shape_Mash_heart_instancer_6" geometry={nodes.myPlane261Shape_Mash_heart_instancer_6.geometry} material={materials.aiStandardSurface3} position={[-18.05, 0.15, -35.48]} rotation={[-1.46, -0.06, 2.4]} scale={0.08} />
          <mesh name="myPlane256Shape_Mash_heart_instancer_7" geometry={nodes.myPlane256Shape_Mash_heart_instancer_7.geometry} material={materials.aiStandardSurface3} position={[-16.14, -5.51, -35.4]} rotation={[1.93, -0.03, 0.61]} scale={0.08} />
          <mesh name="myPlane260Shape_Mash_heart_instancer_8" geometry={nodes.myPlane260Shape_Mash_heart_instancer_8.geometry} material={materials.aiStandardSurface3} position={[-13.76, -10.29, -35.39]} rotation={[1.98, 0, 0.57]} scale={0.08} />
          <mesh name="myPlane264Shape_Mash_heart_instancer_9" geometry={nodes.myPlane264Shape_Mash_heart_instancer_9.geometry} material={materials.aiStandardSurface3} position={[-10.28, -14.89, -35.32]} rotation={[2.11, 0.01, 0.53]} scale={0.09} />
          <mesh name="myPlane265Shape_Mash_heart_instancer_10" geometry={nodes.myPlane265Shape_Mash_heart_instancer_10.geometry} material={materials.aiStandardSurface3} position={[-5.83, -19.31, -35.36]} rotation={[2.13, 0.13, 0.49]} scale={0.08} />
          <mesh name="myPlane266Shape_Mash_heart_instancer_11" geometry={nodes.myPlane266Shape_Mash_heart_instancer_11.geometry} material={materials.aiStandardSurface3} position={[-1.77, -22.76, -35.41]} rotation={[1.93, 0.56, 0.58]} scale={0.07} />
          <mesh name="myPlane267Shape_Mash_heart_instancer_12" geometry={nodes.myPlane267Shape_Mash_heart_instancer_12.geometry} material={materials.aiStandardSurface3} position={[-1.1, -20.08, -33.68]} rotation={[1.67, 0.73, 0.3]} scale={0.07} />
          <mesh name="myPlane271Shape_Mash_heart_instancer_13" geometry={nodes.myPlane271Shape_Mash_heart_instancer_13.geometry} material={materials.aiStandardSurface3} position={[-1.45, -15.4, -32.39]} rotation={[1.65, 0.75, 0.22]} scale={0.07} />
          <mesh name="myPlane269Shape_Mash_heart_instancer_14" geometry={nodes.myPlane269Shape_Mash_heart_instancer_14.geometry} material={materials.aiStandardSurface3} position={[-2.27, -11.12, -31.59]} rotation={[1.67, 0.76, 0.16]} scale={0.09} />
          <mesh name="myPlane270Shape_Mash_heart_instancer_15" geometry={nodes.myPlane270Shape_Mash_heart_instancer_15.geometry} material={materials.aiStandardSurface3} position={[-2.88, -6.83, -31]} rotation={[1.64, 0.74, 0.09]} scale={0.1} />
          <mesh name="myPlane203Shape_Mash_heart_instancer_16" geometry={nodes.myPlane203Shape_Mash_heart_instancer_16.geometry} material={materials.aiStandardSurface3} position={[-3.51, -2.51, -30.55]} rotation={[1.64, 0.76, 0.03]} scale={0.11} />
          <mesh name="myPlane201Shape_Mash_heart_instancer_17" geometry={nodes.myPlane201Shape_Mash_heart_instancer_17.geometry} material={materials.aiStandardSurface3} position={[-4.02, 2.33, -30.38]} rotation={[1.55, 0.77, -0.06]} scale={0.12} />
          <mesh name="myPlane202Shape_Mash_heart_instancer_18" geometry={nodes.myPlane202Shape_Mash_heart_instancer_18.geometry} material={materials.aiStandardSurface3} position={[-4.36, 6.99, -31.66]} rotation={[1.23, 0.78, -0.22]} scale={0.13} />
          <mesh name="myPlane208Shape_Mash_heart_instancer_19" geometry={nodes.myPlane208Shape_Mash_heart_instancer_19.geometry} material={materials.aiStandardSurface3} position={[-12.2, 10.42, -33.4]} rotation={[0.86, 0.72, 0.42]} scale={0.09} />
          <mesh name="myPlane210Shape_Mash_heart_instancer_20" geometry={nodes.myPlane210Shape_Mash_heart_instancer_20.geometry} material={materials.aiStandardSurface3} position={[-13.05, 5.99, -32.63]} rotation={[1.02, 0.72, 0.57]} scale={0.12} />
          <mesh name="myPlane206Shape_Mash_heart_instancer_21" geometry={nodes.myPlane206Shape_Mash_heart_instancer_21.geometry} material={materials.aiStandardSurface3} position={[-12.6, 1.07, -32.25]} rotation={[1.24, 0.75, 0.59]} scale={0.14} />
          <mesh name="myPlane204Shape_Mash_heart_instancer_22" geometry={nodes.myPlane204Shape_Mash_heart_instancer_22.geometry} material={materials.aiStandardSurface3} position={[-11.17, -4.05, -32.32]} rotation={[1.39, 0.75, 0.54]} scale={0.13} />
          <mesh name="myPlane207Shape_Mash_heart_instancer_23" geometry={nodes.myPlane207Shape_Mash_heart_instancer_23.geometry} material={materials.aiStandardSurface3} position={[-9.32, -8.45, -32.74]} rotation={[1.49, 0.72, 0.48]} scale={0.11} />
          <mesh name="myPlane205Shape_Mash_heart_instancer_24" geometry={nodes.myPlane205Shape_Mash_heart_instancer_24.geometry} material={materials.aiStandardSurface3} position={[-7.34, -12.68, -33.33]} rotation={[1.57, 0.74, 0.42]} scale={0.11} />
          <mesh name="myPlane209Shape_Mash_heart_instancer_25" geometry={nodes.myPlane209Shape_Mash_heart_instancer_25.geometry} material={materials.aiStandardSurface3} position={[-4.53, -17.04, -33.67]} rotation={[1.6, 0.75, 0.39]} scale={0.08} />
          <mesh name="myPlane216Shape_Mash_heart_instancer_26" geometry={nodes.myPlane216Shape_Mash_heart_instancer_26.geometry} material={materials.aiStandardSurface3} position={[5.69, 11.01, -33.38]} rotation={[1.35, -0.78, 0.27]} scale={0.11} />
          <mesh name="myPlane218Shape_Mash_heart_instancer_27" geometry={nodes.myPlane218Shape_Mash_heart_instancer_27.geometry} material={materials.aiStandardSurface3} position={[1.85, 11.77, -35.28]} rotation={[-2.09, 0.44, 2.44]} scale={0.07} />
          <mesh name="myPlane215Shape_Mash_heart_instancer_28" geometry={nodes.myPlane215Shape_Mash_heart_instancer_28.geometry} material={materials.aiStandardSurface3} position={[6.83, 14.08, -35.34]} rotation={[-2.73, -1, 2.9]} scale={0.07} />
          <mesh name="myPlane213Shape_Mash_heart_instancer_29" geometry={nodes.myPlane213Shape_Mash_heart_instancer_29.geometry} material={materials.aiStandardSurface3} position={[11.99, 13.6, -35.39]} rotation={[-2.28, -0.43, -2.8]} scale={0.07} />
          <mesh name="myPlane211Shape_Mash_heart_instancer_30" geometry={nodes.myPlane211Shape_Mash_heart_instancer_30.geometry} material={materials.aiStandardSurface3} position={[15.73, 11.06, -35.38]} rotation={[1.07, 0.2, -0.6]} scale={0.07} />
          <mesh name="myPlane217Shape_Mash_heart_instancer_31" geometry={nodes.myPlane217Shape_Mash_heart_instancer_31.geometry} material={materials.aiStandardSurface3} position={[18.09, 6.26, -35.39]} rotation={[-2.01, 0.21, -2.34]} scale={0.08} />
          <mesh name="myPlane224Shape_Mash_heart_instancer_32" geometry={nodes.myPlane224Shape_Mash_heart_instancer_32.geometry} material={materials.aiStandardSurface3} position={[18, 0.24, -35.37]} rotation={[-2.33, 0.72, -2.03]} scale={0.08} />
          <mesh name="myPlane212Shape_Mash_heart_instancer_33" geometry={nodes.myPlane212Shape_Mash_heart_instancer_33.geometry} material={materials.aiStandardSurface3} position={[16.13, -5.5, -35.4]} rotation={[-2.25, 0.88, -2.01]} scale={0.08} />
          <mesh name="myPlane214Shape_Mash_heart_instancer_34" geometry={nodes.myPlane214Shape_Mash_heart_instancer_34.geometry} material={materials.aiStandardSurface3} position={[13.7, -10.29, -35.39]} rotation={[-2.14, 0.91, -2.07]} scale={0.08} />
          <mesh name="myPlane220Shape_Mash_heart_instancer_35" geometry={nodes.myPlane220Shape_Mash_heart_instancer_35.geometry} material={materials.aiStandardSurface3} position={[10.16, -14.93, -35.25]} rotation={[1.15, -0.95, -1.06]} scale={0.09} />
          <mesh name="myPlane223Shape_Mash_heart_instancer_36" geometry={nodes.myPlane223Shape_Mash_heart_instancer_36.geometry} material={materials.aiStandardSurface3} position={[5.78, -19.32, -35.28]} rotation={[1.31, -0.97, -0.98]} scale={0.08} />
          <mesh name="myPlane219Shape_Mash_heart_instancer_37" geometry={nodes.myPlane219Shape_Mash_heart_instancer_37.geometry} material={materials.aiStandardSurface3} position={[1.77, -22.77, -35.41]} rotation={[0.33, -1.06, -1.9]} scale={0.07} />
          <mesh name="myPlane221Shape_Mash_heart_instancer_38" geometry={nodes.myPlane221Shape_Mash_heart_instancer_38.geometry} material={materials.aiStandardSurface3} position={[1.14, -20.16, -33.74]} rotation={[1.67, -0.73, -0.3]} scale={0.07} />
        </group>
        <PerspectiveCamera name="cameraHeart" makeDefault={false} far={10000} fov={37.85} position={[5.75, 0.06, 32.75]} rotation={[-0.03, 0.08, 0]} scale={9.15} />
      </group>
    </group>
  )
}

useGLTF.preload('/Heart.gltf')
