/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  console.log("before useGltf")
  const { nodes, materials } = useGLTF('/soccer.glb')
  console.log("after useGltf")
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={10000} fov={37.85} position={[1.89, 2.17, 5.62]} rotation={[-0.37, 0.3, 0.12]} />
      <mesh geometry={nodes.pSolid1.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/soccer.gltf')
